const NAMESPACE = '@CATEGORY/QUIZ';

const actionTypes = {
  UPDATE_JAVASCRIPT: `${NAMESPACE}/UPDATE_JAVASCRIPT`,
  CREATE_CATEGORY: `${NAMESPACE}/CREATE_CATEGORY`,
  ADD_ANSWER: `${NAMESPACE}/ADD_ANSWER`,
  UPDATE_ANSWER: `${NAMESPACE}/UPDATE_ANSWER`,
};

export default actionTypes;
